if (WIN32)
elseif (APPLE)
    if (NOT SOL_BUILD_HOMEBREW)
        set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
        set(CMAKE_INSTALL_RPATH "")
        set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE)
    endif()
elseif (UNIX)
    include(GNUInstallDirs)

    if(NOT DEFINED SOL_EXECUTABLE_PATH)
        set(SOL_EXECUTABLE_PATH "sol")
    endif()

    if(SOL_BUILD_FLATPAK)
        set(SOL_SERVICE_START_COMMAND "ExecStart=flatpak run --command=sol ${PROJECT_FQDN}")
        set(SOL_SERVICE_STOP_COMMAND "ExecStop=flatpak kill ${PROJECT_FQDN}")
    else()
        set(SOL_SERVICE_START_COMMAND "ExecStart=${SOL_EXECUTABLE_PATH}")
        set(SOL_SERVICE_STOP_COMMAND "")
    endif()
endif()
